site: Minh Phan's Website
title: Minh Phan
greetings: Hello World! 👋
description: >-
  a personal corner
lang: en-US
timezone:  Asia/Vietnam
data-theme: light # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: Minh
  bio: a personal website
  userpicture: 
  username: # general username
  github: minhphan03 # github username
  bluesky: minhphan03.com
  instagram: mnh.p 
  linkedin: mnhp
  flickr: minhphan03
  letterboxd: minhphan
  goodreads: mnhp

# Font Settings
# googlewebfonts: family=EB+Garamond:ital,wght@0,400;0,600;1,400;1,600

# URL settings
url: "https://www.minhph.com" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.

# local
# url: "http://localhost:4000" # 
# baseurl: "/website" # 

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 13
paginate_path: "/blog/page:num/"

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

gems: [jekyll-paginate]